Added code line changed

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -21,6 +21,27 @@ jobs:
       with:
         go-version: '1.20'
 
+    - name: Count lines of code
+      id: loc
+      run: |
+        curl -sLO https://github.com/vearutop/sccdiff/releases/download/v1.0.3/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz
+        sccdiff_hash=$(git hash-object ./sccdiff)
+        [ "$sccdiff_hash" == "ae8a07b687bd3dba60861584efe724351aa7ff63" ] || (echo "::error::unexpected hash for sccdiff, possible tampering: $sccdiff_hash" && exit 1)
+        OUTPUT=$(cd pr && ../sccdiff -basedir ../base)
+        echo "${OUTPUT}"
+        echo "diff<<EOF" >> $GITHUB_OUTPUT && echo "$OUTPUT" >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT
+
+    - name: Comment lines of code
+      continue-on-error: true
+      uses: marocchino/sticky-pull-request-comment@v2
+      with:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        header: LOC
+        message: |
+          ### Lines Of Code
+
+          ${{ steps.loc.outputs.diff }}
+
     - name: Build
       run: go build -v ./...
 
