Fix

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -80,6 +80,7 @@ jobs:
 
     - name: Test
       id: test
+      working-directory: ./pr
       run: |
         go test -short -coverprofile=unit.coverprofile -covermode=atomic -race ./...
         go tool cover -func=./unit.coverprofile > unit.txt
@@ -98,7 +99,7 @@ jobs:
         REP=$(./gocovdiff -mod github.com/$GITHUB_REPOSITORY -cov unit.coverprofile -gha-annotations gha-unit.txt -delta-cov-file delta-cov-unit.txt -target-delta-cov ${TARGET_DELTA_COV})
         echo "${REP}"
         cat gha-unit.txt
-        DIFF=$(test -e unit-base.txt && ./gocovdiff -mod github.com/$GITHUB_REPOSITORY -func-cov unit.txt -func-base-cov unit-base.txt || echo "Missing base coverage file")
+        DIFF=$(test -e ./base/unit-base.txt && ./gocovdiff -mod github.com/$GITHUB_REPOSITORY -func-cov ./pr/unit.txt -func-base-cov unit-base.txt || echo "Missing base coverage file")
         TOTAL=$(cat delta-cov-unit.txt)
         echo "rep<<EOF" >> $GITHUB_OUTPUT && echo "$REP" >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT
         echo "diff<<EOF" >> $GITHUB_OUTPUT && echo "$DIFF" >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT
